---
kind: pipeline
name: fossa

steps:
- name: fossa
  image: rancher/drone-fossa:latest
  failure: ignore
  settings:
    api_key:
      from_secret: FOSSA_API_KEY
    when:
      instance:
        - drone-publish.rancher.io
---
kind: pipeline
name: test

steps:
  - name: test
    image: registry.suse.com/bci/golang:1.23
    commands:
      - make test
    when:
      event:
        - push
        - pull_request
